#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/git-describe-resource-request

cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

# for jq
PATH=/usr/local/bin:$PATH

uri=$(jq -r '.source.uri // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
git_config_payload=$(jq -r '.source.git_config // []' < $payload)

configure_git_global "${git_config_payload}"

destination=$TMPDIR/git-describe-resource-repo-cache

if [ -d $destination ]; then
    cd $destination
    git fetch
    git reset --hard FETCH_HEAD
else
    branchflag=""
    if [ -n "$branch" ]; then
        branchflag="--branch $branch"
    fi

    git clone --single-branch $uri $branchflag $destination
    cd $destination
fi

version=$(git describe)

echo "$version" | jq -R '.' | jq -s "map({ref: .})" >&3
