#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/git-describe-resource-request

cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

uri=$(jq -r '.source.uri // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
git_config_payload=$(jq -r '.source.git_config // []' < $payload)
ref=$(jq -r '.version.ref // "HEAD"' < $payload)

branchflag=""
if [ -n "$branch" ]; then
  branchflag="--branch $branch"
fi

git clone --single-branch $uri $branchflag $destination

cd $destination

git checkout -q $ref

echo $ref >> $destination/version

jq -n "{
  version: {ref: $(echo $ref | jq -R .)},
  metadata: $(git_metadata)
}" >&3
